"""
schema.py - Phase 2 Structured Construction Inspection Data Models & Schema for CivilVision AI
Defines controlled inspection categories, evidence boundaries, confidence levels,
risk priorities, and typed data models for structured visual inspections.
"""

from dataclasses import dataclass, field, asdict
from typing import List, Optional, Dict, Any, Tuple
import json
import re


# ---------------------------------------------------------
# Phase 2.1 Controlled Inspection Categories
# ---------------------------------------------------------
INSPECTION_CATEGORIES = [
    "Structural / Concrete",
    "Formwork & Shoring",
    "Scaffolding",
    "Site Safety",
    "PPE",
    "Equipment / Machinery",
    "Materials",
    "Housekeeping / Site Conditions",
    "Work Progress",
]

# ---------------------------------------------------------
# Phase 2.2 & 2.4 Controlled Enums / Literals
# ---------------------------------------------------------
VISUAL_CONFIDENCE_LEVELS = [
    "HIGH",
    "MEDIUM",
    "REQUIRES_PHYSICAL_VERIFICATION",
]

RISK_PRIORITIES = [
    "HIGH ATTENTION",
    "MEDIUM ATTENTION",
    "LOW ATTENTION",
]

EVIDENCE_TYPES = [
    "VISIBLE",
    "INFERRED",
    "NOT_DETERMINABLE",
]

# Physical verification trigger keywords (engineering parameters 2D photos cannot determine)
PHYSICAL_VERIFICATION_KEYWORDS = [
    "concrete strength",
    "compressive strength",
    "concrete grade",
    "reinforcement diameter",
    "rebar diameter",
    "rebar size",
    "reinforcement spacing",
    "rebar spacing",
    "reinforcement cover",
    "cover depth",
    "structural load capacity",
    "bearing capacity",
    "foundation condition",
    "subsurface",
    "hidden connections",
    "weld integrity",
    "anchorage capacity",
    "anchor torque",
    "coupler torque",
    "code compliance",
    "plumbness",
    "structural adequacy",
]


@dataclass
class ObservationRecord:
    """
    Structured inspection record for a single visual observation on site.
    """
    category: str
    observation: str
    visual_confidence: str
    potential_issue: str
    physical_verification_required: str
    recommended_action: str
    risk_priority: str
    evidence_type: str = "VISIBLE"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def validate(self) -> List[str]:
        """
        Validates the record against CivilVision AI rules:
        - Category must match controlled list
        - Visual confidence must be HIGH, MEDIUM, or REQUIRES_PHYSICAL_VERIFICATION
        - Risk priority must be HIGH ATTENTION, MEDIUM ATTENTION, or LOW ATTENTION
        - No arbitrary numerical percentages
        - Physical verification triggers must enforce REQUIRES_PHYSICAL_VERIFICATION
        """
        errors = []
        # Category validation
        if self.category not in INSPECTION_CATEGORIES:
            # Check for close match or normalize
            matched = next((c for c in INSPECTION_CATEGORIES if c.lower() == self.category.lower()), None)
            if not matched:
                errors.append(f"Invalid category '{self.category}'. Must be one of {INSPECTION_CATEGORIES}")

        # Confidence validation
        if self.visual_confidence not in VISUAL_CONFIDENCE_LEVELS:
            errors.append(
                f"Invalid visual_confidence '{self.visual_confidence}'. Must be one of {VISUAL_CONFIDENCE_LEVELS}"
            )

        # Risk priority validation
        if self.risk_priority not in RISK_PRIORITIES:
            errors.append(
                f"Invalid risk_priority '{self.risk_priority}'. Must be one of {RISK_PRIORITIES}"
            )

        # No percentage check
        all_text = f"{self.observation} {self.potential_issue} {self.physical_verification_required} {self.recommended_action}"
        if re.search(r"\b\d{1,3}%", all_text) or "percent" in all_text.lower():
            errors.append("Forbidden numerical confidence percentage detected in observation text.")

        # Physical verification enforcement
        for trigger in PHYSICAL_VERIFICATION_KEYWORDS:
            if trigger in self.observation.lower() and "cannot" not in self.observation.lower() and "unable" not in self.observation.lower():
                if self.visual_confidence == "HIGH":
                    errors.append(
                        f"Physical verification parameter '{trigger}' cannot be classified as HIGH visual confidence."
                    )

        return errors


@dataclass
class InspectionReport:
    """
    Complete structured inspection report for a construction site image.
    """
    summary: str
    observations: List[ObservationRecord] = field(default_factory=list)
    site_activity: str = ""
    disclaimer: str = (
        "This visual inspection report is generated by CivilVision AI as a preliminary visual screening tool. "
        "Visual assessment does not replace mandatory physical inspection, non-destructive testing (NDT), "
        "or licensed professional engineering sign-offs."
    )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "summary": self.summary,
            "site_activity": self.site_activity,
            "observations": [obs.to_dict() for obs in self.observations],
            "disclaimer": self.disclaimer,
        }


# ---------------------------------------------------------
# Phase 3A Inspection Record & Session History Data Models
# ---------------------------------------------------------
import uuid
import datetime


def generate_inspection_id(prefix: str = "CV") -> str:
    """
    Generates a unique local inspection ID formatted as:
    CV-YYYYMMDD-HHMMSS-XXXX
    Contains no personally identifying information.
    """
    now = datetime.datetime.now()
    timestamp_str = now.strftime("%Y%m%d-%H%M%S")
    rand_suffix = uuid.uuid4().hex[:4].upper()
    return f"{prefix}-{timestamp_str}-{rand_suffix}"


@dataclass
class InspectionRecord:
    """
    Phase 3A Reusable inspection record representing a completed visual inspection.
    Enables session-based review, local filtering, and history inspection without
    making additional API calls.
    """
    inspection_id: str
    timestamp: str
    site_activity: str
    executive_summary: str
    observations: List[ObservationRecord] = field(default_factory=list)
    disclaimer: str = (
        "This visual inspection report is generated by CivilVision AI as a preliminary visual screening tool. "
        "Visual assessment does not replace mandatory physical inspection, non-destructive testing (NDT), "
        "or licensed professional engineering sign-offs."
    )
    source_image_name: Optional[str] = None
    source_image_size_kb: Optional[float] = None
    source_image_dimensions: Optional[str] = None

    @classmethod
    def from_report(
        cls,
        report: InspectionReport,
        inspection_id: Optional[str] = None,
        source_image_name: Optional[str] = None,
        source_image_size_kb: Optional[float] = None,
        source_image_dimensions: Optional[str] = None,
        timestamp: Optional[str] = None,
    ) -> "InspectionRecord":
        """Factory constructor creating an InspectionRecord directly from an existing InspectionReport."""
        iid = inspection_id or generate_inspection_id()
        ts = timestamp or datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return cls(
            inspection_id=iid,
            timestamp=ts,
            site_activity=report.site_activity or report.summary,
            executive_summary=report.summary,
            observations=list(report.observations),
            disclaimer=report.disclaimer,
            source_image_name=source_image_name,
            source_image_size_kb=source_image_size_kb,
            source_image_dimensions=source_image_dimensions,
        )

    @property
    def total_observations(self) -> int:
        return len(self.observations)

    @property
    def high_attention_count(self) -> int:
        return sum(1 for o in self.observations if o.risk_priority == "HIGH ATTENTION")

    @property
    def medium_attention_count(self) -> int:
        return sum(1 for o in self.observations if o.risk_priority == "MEDIUM ATTENTION")

    @property
    def low_attention_count(self) -> int:
        return sum(1 for o in self.observations if o.risk_priority == "LOW ATTENTION")

    @property
    def visible_evidence_count(self) -> int:
        return sum(1 for o in self.observations if o.evidence_type == "VISIBLE")

    @property
    def inferred_evidence_count(self) -> int:
        return sum(1 for o in self.observations if o.evidence_type == "INFERRED")

    @property
    def not_determinable_evidence_count(self) -> int:
        return sum(1 for o in self.observations if o.evidence_type == "NOT_DETERMINABLE")

    @property
    def evidence_counts(self) -> Dict[str, int]:
        return {
            "VISIBLE": self.visible_evidence_count,
            "INFERRED": self.inferred_evidence_count,
            "NOT_DETERMINABLE": self.not_determinable_evidence_count,
        }

    def to_dict(self) -> Dict[str, Any]:
        return {
            "inspection_id": self.inspection_id,
            "timestamp": self.timestamp,
            "site_activity": self.site_activity,
            "executive_summary": self.executive_summary,
            "observations": [o.to_dict() for o in self.observations],
            "disclaimer": self.disclaimer,
            "source_image_name": self.source_image_name,
            "source_image_size_kb": self.source_image_size_kb,
            "source_image_dimensions": self.source_image_dimensions,
            "counts": {
                "total": self.total_observations,
                "high": self.high_attention_count,
                "medium": self.medium_attention_count,
                "low": self.low_attention_count,
                "visible": self.visible_evidence_count,
                "inferred": self.inferred_evidence_count,
                "not_determinable": self.not_determinable_evidence_count,
            },
        }

    def to_report(self) -> InspectionReport:
        """Converts back to an InspectionReport for display components."""
        return InspectionReport(
            summary=self.executive_summary,
            observations=list(self.observations),
            site_activity=self.site_activity,
            disclaimer=self.disclaimer,
        )


def filter_inspection_records(
    records: List[InspectionRecord],
    category: Optional[str] = None,
    priority: Optional[str] = None,
    reverse_chronological: bool = True,
) -> List[InspectionRecord]:
    """
    Pure local filtering on existing inspection records.
    Requires ZERO external or Gemini API calls.
    """
    res = list(records)
    if reverse_chronological:
        # Latest first (records are naturally inserted chronologically or sorted by timestamp)
        res = list(reversed(res))

    if category and category != "All Categories":
        res = [
            rec for rec in res
            if any(obs.category == category for obs in rec.observations)
        ]

    if priority and priority != "All Priorities":
        norm_prio = normalize_risk_priority(priority)
        res = [
            rec for rec in res
            if any(obs.risk_priority == norm_prio for obs in rec.observations)
        ]

    return res


# ---------------------------------------------------------
# Phase 4B Workspace & Workflow Hardening Helpers
# ---------------------------------------------------------

def reset_current_workspace(session_state_dict: Dict[str, Any]) -> None:
    """
    Hardens the workspace by resetting transient current-inspection state while
    strictly preserving:
    - inspection_history
    - historical records
    - selected_historical_inspection_id
    - application configuration
    Zero Gemini calls.
    """
    session_state_dict["image_bytes"] = None
    session_state_dict["image_mime"] = None
    session_state_dict["image_name"] = None
    session_state_dict["analysis_result"] = None
    session_state_dict["structured_inspection"] = None
    session_state_dict["analysis_fallback"] = None
    session_state_dict["summary_fallback"] = None
    session_state_dict["last_chat_fallback"] = None
    session_state_dict["chat_history"] = []
    session_state_dict["inspection_summary"] = None
    session_state_dict["pending_prompt"] = None
    session_state_dict["current_inspection_id"] = None


def select_historical_inspection(session_state_dict: Dict[str, Any], inspection_id: str) -> Optional[InspectionRecord]:
    """
    Selects a historical inspection for read-only viewing without overwriting or
    mutating current inspection state.
    Zero Gemini calls.
    """
    history = session_state_dict.get("inspection_history", [])
    rec = next((r for r in history if r.inspection_id == inspection_id), None)
    if rec:
        session_state_dict["selected_historical_inspection_id"] = inspection_id
    return rec


def get_current_inspection(session_state_dict: Dict[str, Any]) -> Optional[InspectionRecord]:
    """
    Retrieves the active inspection record from current workspace state.
    Zero Gemini calls.
    """
    curr_id = session_state_dict.get("current_inspection_id")
    history = session_state_dict.get("inspection_history", [])
    if curr_id:
        rec = next((r for r in history if r.inspection_id == curr_id), None)
        if rec:
            return rec
    report = session_state_dict.get("structured_inspection")
    if report and getattr(report, "observations", None):
        return InspectionRecord.from_report(
            report=report,
            inspection_id=curr_id,
            source_image_name=session_state_dict.get("image_name"),
            source_image_size_kb=round(len(session_state_dict["image_bytes"]) / 1024, 1) if session_state_dict.get("image_bytes") else None,
        )
    return None


def get_selected_historical_inspection(session_state_dict: Dict[str, Any]) -> Optional[InspectionRecord]:
    """
    Retrieves the currently selected read-only historical inspection record.
    Zero Gemini calls.
    """
    sel_id = session_state_dict.get("selected_historical_inspection_id")
    history = session_state_dict.get("inspection_history", [])
    if sel_id:
        return next((r for r in history if r.inspection_id == sel_id), None)
    return None


# ---------------------------------------------------------
# Phase 3B Inspection Comparison Data Models & Helpers
# ---------------------------------------------------------

@dataclass
class InspectionComparisonResult:
    """
    Structured outcome of comparing two InspectionRecords.
    Calculated 100% locally with zero external or Gemini API calls.
    Differences are calculated as: Inspection B - Inspection A.
    """
    record_a: InspectionRecord
    record_b: InspectionRecord
    total_obs_a: int
    total_obs_b: int
    total_obs_diff: int
    priority_counts_a: Dict[str, int]
    priority_counts_b: Dict[str, int]
    priority_diffs: Dict[str, int]
    confidence_counts_a: Dict[str, int]
    confidence_counts_b: Dict[str, int]
    confidence_diffs: Dict[str, int]
    category_counts_a: Dict[str, int]
    category_counts_b: Dict[str, int]
    category_diffs: Dict[str, int]
    change_summary_statements: List[str]
    is_same_record: bool = False
    error_message: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "record_a_id": self.record_a.inspection_id,
            "record_b_id": self.record_b.inspection_id,
            "is_same_record": self.is_same_record,
            "error_message": self.error_message,
            "total_obs_a": self.total_obs_a,
            "total_obs_b": self.total_obs_b,
            "total_obs_diff": self.total_obs_diff,
            "priority_counts_a": self.priority_counts_a,
            "priority_counts_b": self.priority_counts_b,
            "priority_diffs": self.priority_diffs,
            "confidence_counts_a": self.confidence_counts_a,
            "confidence_counts_b": self.confidence_counts_b,
            "confidence_diffs": self.confidence_diffs,
            "category_counts_a": self.category_counts_a,
            "category_counts_b": self.category_counts_b,
            "category_diffs": self.category_diffs,
            "change_summary_statements": self.change_summary_statements,
        }


def compare_priority_counts(
    record_a: InspectionRecord,
    record_b: InspectionRecord,
) -> Tuple[Dict[str, int], Dict[str, int], Dict[str, int]]:
    """
    Computes priority counts and differences (B - A) for HIGH, MEDIUM, and LOW ATTENTION.
    """
    counts_a = {
        "HIGH ATTENTION": record_a.high_attention_count,
        "MEDIUM ATTENTION": record_a.medium_attention_count,
        "LOW ATTENTION": record_a.low_attention_count,
    }
    counts_b = {
        "HIGH ATTENTION": record_b.high_attention_count,
        "MEDIUM ATTENTION": record_b.medium_attention_count,
        "LOW ATTENTION": record_b.low_attention_count,
    }
    diffs = {
        prio: counts_b[prio] - counts_a[prio]
        for prio in ["HIGH ATTENTION", "MEDIUM ATTENTION", "LOW ATTENTION"]
    }
    return counts_a, counts_b, diffs


def compare_confidence_counts(
    record_a: InspectionRecord,
    record_b: InspectionRecord,
) -> Tuple[Dict[str, int], Dict[str, int], Dict[str, int]]:
    """
    Computes visual confidence counts and differences (B - A) for HIGH, MEDIUM,
    and REQUIRES_PHYSICAL_VERIFICATION.
    """
    levels = ["HIGH", "MEDIUM", "REQUIRES_PHYSICAL_VERIFICATION"]
    counts_a = {
        lvl: sum(1 for o in record_a.observations if o.visual_confidence == lvl)
        for lvl in levels
    }
    counts_b = {
        lvl: sum(1 for o in record_b.observations if o.visual_confidence == lvl)
        for lvl in levels
    }
    diffs = {lvl: counts_b[lvl] - counts_a[lvl] for lvl in levels}
    return counts_a, counts_b, diffs


def compare_category_counts(
    record_a: InspectionRecord,
    record_b: InspectionRecord,
) -> Tuple[Dict[str, int], Dict[str, int], Dict[str, int]]:
    """
    Computes observation counts per category for all categories present in either
    inspection (or across controlled categories), and differences (B - A).
    Categories existing in only one inspection report 0 for the other.
    """
    cats_present = sorted(list(
        {o.category for o in record_a.observations}.union(
            {o.category for o in record_b.observations}
        )
    ))
    # Fallback to controlled list if both records have 0 observations
    if not cats_present:
        cats_present = list(INSPECTION_CATEGORIES)

    counts_a = {
        cat: sum(1 for o in record_a.observations if o.category == cat)
        for cat in cats_present
    }
    counts_b = {
        cat: sum(1 for o in record_b.observations if o.category == cat)
        for cat in cats_present
    }
    diffs = {cat: counts_b[cat] - counts_a[cat] for cat in cats_present}
    return counts_a, counts_b, diffs


def generate_change_summary(
    record_a: InspectionRecord,
    record_b: InspectionRecord,
) -> List[str]:
    """
    Generates neutral, purely factual change summary statements based strictly on
    structured counts and category differences.
    Avoids subjective conclusions like 'site safety improved', 'better', or 'safer'.
    """
    statements = []
    
    # Total observation difference
    total_diff = record_b.total_observations - record_a.total_observations
    if total_diff > 0:
        statements.append(f"Inspection B contains {total_diff} more observation(s) than Inspection A ({record_b.total_observations} vs {record_a.total_observations}).")
    elif total_diff < 0:
        statements.append(f"Inspection B contains {abs(total_diff)} fewer observation(s) than Inspection A ({record_b.total_observations} vs {record_a.total_observations}).")
    else:
        statements.append(f"Both inspections contain an equal total number of observations ({record_a.total_observations}).")

    # High attention difference
    high_diff = record_b.high_attention_count - record_a.high_attention_count
    if high_diff > 0:
        statements.append(f"Inspection B contains {high_diff} more HIGH ATTENTION observation(s) than Inspection A ({record_b.high_attention_count} vs {record_a.high_attention_count}).")
    elif high_diff < 0:
        statements.append(f"Inspection B contains {abs(high_diff)} fewer HIGH ATTENTION observation(s) than Inspection A ({record_b.high_attention_count} vs {record_a.high_attention_count}).")
    else:
        statements.append(f"HIGH ATTENTION count remained unchanged ({record_a.high_attention_count}).")

    # Medium attention difference
    med_diff = record_b.medium_attention_count - record_a.medium_attention_count
    if med_diff != 0:
        change_word = "more" if med_diff > 0 else "fewer"
        statements.append(f"Inspection B contains {abs(med_diff)} {change_word} MEDIUM ATTENTION observation(s) than Inspection A.")

    # Low attention difference
    low_diff = record_b.low_attention_count - record_a.low_attention_count
    if low_diff != 0:
        change_word = "more" if low_diff > 0 else "fewer"
        statements.append(f"Inspection B contains {abs(low_diff)} {change_word} LOW ATTENTION observation(s) than Inspection A.")

    # Category changes
    cats_a = {o.category for o in record_a.observations}
    cats_b = {o.category for o in record_b.observations}
    new_in_b = sorted(list(cats_b - cats_a))
    absent_in_b = sorted(list(cats_a - cats_b))
    
    if new_in_b:
        statements.append(f"Inspection B contains observation(s) in category(ies) not recorded in Inspection A: {', '.join(new_in_b)}.")
    if absent_in_b:
        statements.append(f"Category(ies) observed in Inspection A not recorded in Inspection B: {', '.join(absent_in_b)}.")

    # Physical verification count
    pv_a = sum(1 for o in record_a.observations if o.visual_confidence == "REQUIRES_PHYSICAL_VERIFICATION")
    pv_b = sum(1 for o in record_b.observations if o.visual_confidence == "REQUIRES_PHYSICAL_VERIFICATION")
    pv_diff = pv_b - pv_a
    if pv_diff != 0:
        change_word = "increased" if pv_diff > 0 else "decreased"
        statements.append(f"Items requiring physical verification {change_word} from {pv_a} in Inspection A to {pv_b} in Inspection B.")

    return statements


def compare_inspection_records(
    record_a: InspectionRecord,
    record_b: InspectionRecord,
) -> InspectionComparisonResult:
    """
    Compares two InspectionRecord instances locally and returns an InspectionComparisonResult.
    Handles same-record comparison and empty observation records safely.
    Zero external/Gemini calls.
    """
    is_same = (record_a.inspection_id == record_b.inspection_id)
    total_a = record_a.total_observations
    total_b = record_b.total_observations
    total_diff = total_b - total_a

    prio_a, prio_b, prio_diff = compare_priority_counts(record_a, record_b)
    conf_a, conf_b, conf_diff = compare_confidence_counts(record_a, record_b)
    cat_a, cat_b, cat_diff = compare_category_counts(record_a, record_b)
    
    if is_same:
        summary_stmts = [
            f"Inspection A and Inspection B are identical records ({record_a.inspection_id}). Comparison is not meaningful."
        ]
        err_msg = f"Cannot compare inspection {record_a.inspection_id} with itself. Please select two different inspections."
    else:
        summary_stmts = generate_change_summary(record_a, record_b)
        err_msg = None

    return InspectionComparisonResult(
        record_a=record_a,
        record_b=record_b,
        total_obs_a=total_a,
        total_obs_b=total_b,
        total_obs_diff=total_diff,
        priority_counts_a=prio_a,
        priority_counts_b=prio_b,
        priority_diffs=prio_diff,
        confidence_counts_a=conf_a,
        confidence_counts_b=conf_b,
        confidence_diffs=conf_diff,
        category_counts_a=cat_a,
        category_counts_b=cat_b,
        category_diffs=cat_diff,
        change_summary_statements=summary_stmts,
        is_same_record=is_same,
        error_message=err_msg,
    )


# ---------------------------------------------------------
# Phase 3C Inspection Report Generation Foundation Data Models & Helpers
# ---------------------------------------------------------

@dataclass
class InspectionReportRepresentation:
    """
    Phase 3C Reusable structured report representation of an InspectionRecord.
    Forms the local foundation for human-readable presentation and export formats.
    Generated 100% locally from stored structured inspection data without any Gemini calls.
    """
    report_title: str
    inspection_id: str
    timestamp: str
    site_activity: str
    executive_summary: str
    observation_counts: Dict[str, int]
    categorized_observations: Dict[str, List[ObservationRecord]]
    disclaimer: str
    source_image_name: Optional[str] = None
    source_image_size_kb: Optional[float] = None
    source_image_dimensions: Optional[str] = None
    evidence_counts: Dict[str, int] = field(default_factory=lambda: {"VISIBLE": 0, "INFERRED": 0, "NOT_DETERMINABLE": 0})

    def to_dict(self) -> Dict[str, Any]:
        return {
            "report_title": self.report_title,
            "inspection_id": self.inspection_id,
            "timestamp": self.timestamp,
            "site_activity": self.site_activity,
            "executive_summary": self.executive_summary,
            "observation_counts": self.observation_counts,
            "evidence_counts": self.evidence_counts,
            "categorized_observations": {
                cat: [obs.to_dict() for obs in obs_list]
                for cat, obs_list in self.categorized_observations.items()
            },
            "disclaimer": self.disclaimer,
            "source_image_name": self.source_image_name,
            "source_image_size_kb": self.source_image_size_kb,
            "source_image_dimensions": self.source_image_dimensions,
        }


def generate_inspection_report(record: InspectionRecord) -> InspectionReportRepresentation:
    """
    Generates a structured, deterministic report representation from an InspectionRecord.
    - Preserves existing INSPECTION_CATEGORIES ordering where applicable.
    - Preserves observation ordering within categories.
    - Safely handles zero observations, empty fields, and optional image metadata.
    - ZERO Gemini API or network calls.
    """
    # Counts
    counts = {
        "total": record.total_observations,
        "HIGH ATTENTION": record.high_attention_count,
        "MEDIUM ATTENTION": record.medium_attention_count,
        "LOW ATTENTION": record.low_attention_count,
    }

    # Group observations preserving controlled category order
    grouped: Dict[str, List[ObservationRecord]] = {}
    
    # First, populate categories present in the controlled list in their canonical order
    for cat in INSPECTION_CATEGORIES:
        matching = [o for o in record.observations if o.category == cat]
        if matching:
            grouped[cat] = matching

    # Second, include any other categories present in the record that might not be in the canonical list
    canonical_set = set(INSPECTION_CATEGORIES)
    for obs in record.observations:
        if obs.category not in canonical_set and obs.category not in grouped:
            grouped[obs.category] = [o for o in record.observations if o.category == obs.category]

    title = f"CivilVision AI Site Visual Inspection Report — {record.inspection_id}"
    activity = record.site_activity.strip() if record.site_activity else "General site inspection activity"
    summary = record.executive_summary.strip() if record.executive_summary else "No executive summary provided."
    disclaimer = record.disclaimer.strip() if record.disclaimer else (
        "This visual inspection report is generated by CivilVision AI as a preliminary visual screening tool. "
        "Visual assessment does not replace mandatory physical inspection, non-destructive testing (NDT), "
        "or licensed professional engineering sign-offs."
    )

    return InspectionReportRepresentation(
        report_title=title,
        inspection_id=record.inspection_id,
        timestamp=record.timestamp,
        site_activity=activity,
        executive_summary=summary,
        observation_counts=counts,
        evidence_counts=record.evidence_counts,
        categorized_observations=grouped,
        disclaimer=disclaimer,
        source_image_name=record.source_image_name,
        source_image_size_kb=record.source_image_size_kb,
        source_image_dimensions=record.source_image_dimensions,
    )


def export_inspection_to_csv(record: InspectionRecord) -> str:
    """
    Exports structured observation records from an InspectionRecord to standard CSV format.
    Zero external dependencies and zero Gemini API calls.
    Handles commas, quotes, and newlines safely with Python's standard csv module.
    """
    import csv
    import io

    output = io.StringIO()
    fieldnames = [
        "inspection_id",
        "timestamp",
        "site_activity",
        "category",
        "risk_priority",
        "visual_confidence",
        "evidence_type",
        "observation",
        "potential_issue",
        "physical_verification_required",
        "recommended_action",
    ]
    writer = csv.DictWriter(output, fieldnames=fieldnames, lineterminator="\n")
    writer.writeheader()

    if not record.observations:
        # Return header only for empty observations
        return output.getvalue()

    for obs in record.observations:
        writer.writerow({
            "inspection_id": record.inspection_id,
            "timestamp": record.timestamp,
            "site_activity": record.site_activity,
            "category": obs.category,
            "risk_priority": obs.risk_priority,
            "visual_confidence": obs.visual_confidence,
            "evidence_type": obs.evidence_type,
            "observation": obs.observation,
            "potential_issue": obs.potential_issue,
            "physical_verification_required": obs.physical_verification_required,
            "recommended_action": obs.recommended_action,
        })

    return output.getvalue()


# ---------------------------------------------------------
# Phase 3D PDF Inspection Report Generator (ReportLab Platypus)
# ---------------------------------------------------------
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and print accurate 'Page X of Y' footers
    and professional header rules across all pages.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColorRGB(0.4, 0.45, 0.5)

        # Header (Pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, "CivilVision AI • Construction Site Visual Inspection Report")
            self.setStrokeColorRGB(0.8, 0.82, 0.85)
            self.setLineWidth(0.5)
            self.line(54, 744, 558, 744)

        # Footer (All pages)
        self.setStrokeColorRGB(0.8, 0.82, 0.85)
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)

        footer_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 32, footer_text)
        self.drawString(54, 32, "Confidential • Visual Screening Only • Not Licensed Professional Sign-Off")
        self.restoreState()


def generate_inspection_pdf(report: InspectionReportRepresentation) -> bytes:
    """
    Generates a professional engineering PDF report from an InspectionReportRepresentation.
    Operates in memory and returns raw PDF bytes.
    Zero external network or Gemini API calls.
    """
    import io
    from reportlab import rl_config
    # Ensure uncompressed ASCII streams for deterministic and inspectable PDF generation
    rl_config.pageCompression = 0
    rl_config.useA85 = 0

    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import (
        SimpleDocTemplate,
        Paragraph,
        Spacer,
        Table,
        TableStyle,
        KeepTogether,
        HRFlowable,
    )

    pdf_buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "DocSubTitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#475569"),
        spaceAfter=12,
    )
    h1_style = ParagraphStyle(
        "SectionH1",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#1E293B"),
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True,
    )
    h2_style = ParagraphStyle(
        "CategoryH2",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#0284C7"),
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True,
    )
    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#1E293B"),
    )
    label_style = ParagraphStyle(
        "ReportLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#0F172A"),
    )
    disclaimer_style = ParagraphStyle(
        "ReportDisclaimer",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#475569"),
    )

    story = []

    # Title & Header
    story.append(Paragraph("CivilVision AI", title_style))
    story.append(Paragraph("Site Visual Inspection & Engineering Screening Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0284C7"), spaceAfter=10))

    # Meta Table (Inspection ID, Timestamp, Source Image)
    img_meta_str = "N/A"
    if report.source_image_name:
        size_part = f" ({report.source_image_size_kb} KB)" if report.source_image_size_kb else ""
        dim_part = f" [{report.source_image_dimensions}]" if report.source_image_dimensions else ""
        img_meta_str = f"{report.source_image_name}{size_part}{dim_part}"

    meta_data = [
        [
            Paragraph("<b>Inspection ID:</b>", label_style),
            Paragraph(f"<font color='#B45309'><b>{report.inspection_id}</b></font>", body_style),
            Paragraph("<b>Date / Time:</b>", label_style),
            Paragraph(report.timestamp, body_style),
        ],
        [
            Paragraph("<b>Source Image:</b>", label_style),
            Paragraph(img_meta_str, body_style),
            Paragraph("<b>Inspection Mode:</b>", label_style),
            Paragraph("Photographic Visual Screening", body_style),
        ],
    ]
    meta_table = Table(meta_data, colWidths=[100, 152, 90, 162])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # Site Information
    story.append(Paragraph("Site Information", h1_style))
    site_info_data = [
        [Paragraph("<b>Site Activity:</b>", label_style), Paragraph(report.site_activity, body_style)],
        [Paragraph("<b>Executive Summary:</b>", label_style), Paragraph(report.executive_summary, body_style)],
    ]
    site_table = Table(site_info_data, colWidths=[110, 394])
    site_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFFFFF")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(site_table)
    story.append(Spacer(1, 10))

    # Observation Summary Counts
    story.append(Paragraph("Observation Summary", h1_style))
    counts = report.observation_counts
    c_tot = counts.get("total", 0)
    c_hi = counts.get("HIGH ATTENTION", 0)
    c_med = counts.get("MEDIUM ATTENTION", 0)
    c_lo = counts.get("LOW ATTENTION", 0)

    summary_counts_data = [
        [
            Paragraph("<b>Total Observations</b>", label_style),
            Paragraph("<b>HIGH ATTENTION</b>", label_style),
            Paragraph("<b>MEDIUM ATTENTION</b>", label_style),
            Paragraph("<b>LOW ATTENTION</b>", label_style),
        ],
        [
            Paragraph(f"<font size='13'><b>{c_tot}</b></font>", body_style),
            Paragraph(f"<font size='13' color='#DC2626'><b>{c_hi}</b></font>", body_style),
            Paragraph(f"<font size='13' color='#D97706'><b>{c_med}</b></font>", body_style),
            Paragraph(f"<font size='13' color='#059669'><b>{c_lo}</b></font>", body_style),
        ],
    ]
    summary_counts_table = Table(summary_counts_data, colWidths=[126, 126, 126, 126])
    summary_counts_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#FFFFFF")),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(summary_counts_table)
    story.append(Spacer(1, 8))

    # Evidence Summary Counts
    story.append(Paragraph("Evidence Summary", h1_style))
    ev_counts = report.evidence_counts
    c_vis = ev_counts.get("VISIBLE", 0)
    c_inf = ev_counts.get("INFERRED", 0)
    c_nd = ev_counts.get("NOT_DETERMINABLE", 0)

    evidence_counts_data = [
        [
            Paragraph("<b>VISIBLE Evidence</b>", label_style),
            Paragraph("<b>INFERRED Evidence</b>", label_style),
            Paragraph("<b>NOT_DETERMINABLE Evidence</b>", label_style),
        ],
        [
            Paragraph(f"<font size='13' color='#0284C7'><b>VISIBLE: {c_vis}</b></font>", body_style),
            Paragraph(f"<font size='13' color='#D97706'><b>INFERRED: {c_inf}</b></font>", body_style),
            Paragraph(f"<font size='13' color='#64748B'><b>NOT_DETERMINABLE: {c_nd}</b></font>", body_style),
        ],
    ]
    evidence_counts_table = Table(evidence_counts_data, colWidths=[168, 168, 168])
    evidence_counts_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F8FAFC")),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#FFFFFF")),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(evidence_counts_table)
    story.append(Spacer(1, 12))

    # Detailed Observations Grouped by Category
    story.append(Paragraph("Detailed Inspection Observations", h1_style))
    story.append(Paragraph(
        "Observations are grouped by controlled category. Visual confidence separates directly observable facts from parameters requiring physical verification.",
        subtitle_style,
    ))

    if not report.categorized_observations:
        story.append(Paragraph("<i>No visual observations recorded in this inspection.</i>", body_style))
        story.append(Spacer(1, 10))
    else:
        for cat_name, obs_list in report.categorized_observations.items():
            cat_header = Paragraph(f"<b>{cat_name}</b> ({len(obs_list)} item{'s' if len(obs_list) != 1 else ''})", h2_style)
            story.append(cat_header)

            for idx, obs in enumerate(obs_list, 1):
                prio_hex = "#DC2626" if obs.risk_priority == "HIGH ATTENTION" else ("#059669" if obs.risk_priority == "LOW ATTENTION" else "#D97706")

                obs_rows = [
                    [
                        Paragraph(f"<b>Observation #{idx}:</b>", label_style),
                        Paragraph(f"{obs.observation}", body_style),
                    ],
                    [
                        Paragraph("<b>Classification:</b>", label_style),
                        Paragraph(
                            f"<font color='{prio_hex}'><b>{obs.risk_priority}</b></font> &nbsp;|&nbsp; "
                            f"<b>Confidence:</b> {obs.visual_confidence} &nbsp;|&nbsp; "
                            f"<b>Evidence:</b> {obs.evidence_type}",
                            body_style,
                        ),
                    ],
                    [
                        Paragraph("<b>Potential Issue / Risk:</b>", label_style),
                        Paragraph(obs.potential_issue, body_style),
                    ],
                    [
                        Paragraph("<b>Physical Verification Required:</b>", label_style),
                        Paragraph(obs.physical_verification_required, body_style),
                    ],
                    [
                        Paragraph("<b>Recommended Action:</b>", label_style),
                        Paragraph(obs.recommended_action, body_style),
                    ],
                ]

                obs_table = Table(obs_rows, colWidths=[120, 384])
                obs_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FAFAFA")),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ]))
                story.append(KeepTogether([obs_table, Spacer(1, 6)]))

            story.append(Spacer(1, 4))

    # Engineering Disclaimer Box
    story.append(Spacer(1, 8))
    story.append(Paragraph("Engineering Limitations & Legal Disclaimer", h1_style))
    disclaimer_table = Table(
        [[Paragraph(f"<b>Mandatory Notice:</b> {report.disclaimer}", disclaimer_style)]],
        colWidths=[504],
    )
    disclaimer_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#94A3B8")),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(disclaimer_table)

    # Build PDF with two-pass numbered canvas
    doc.build(story, canvasmaker=NumberedCanvas)
    return pdf_buffer.getvalue()


def normalize_category(cat: str) -> str:
    """Normalizes raw category string to standard controlled categories."""
    cat_clean = cat.strip().lower()
    for official in INSPECTION_CATEGORIES:
        if cat_clean == official.lower():
            return official
        if official.lower() in cat_clean or cat_clean in official.lower():
            return official
    # Fallback keyword matching
    if "concrete" in cat_clean or "structur" in cat_clean:
        return "Structural / Concrete"
    if "formwork" in cat_clean or "shoring" in cat_clean or "falsework" in cat_clean:
        return "Formwork & Shoring"
    if "scaffold" in cat_clean:
        return "Scaffolding"
    if "ppe" in cat_clean or "helmet" in cat_clean or "vest" in cat_clean:
        return "PPE"
    if "safety" in cat_clean or "guardrail" in cat_clean or "fall" in cat_clean:
        return "Site Safety"
    if "equip" in cat_clean or "crane" in cat_clean or "machin" in cat_clean or "plant" in cat_clean:
        return "Equipment / Machinery"
    if "material" in cat_clean or "rebar" in cat_clean or "steel" in cat_clean:
        return "Materials"
    if "housekeep" in cat_clean or "debris" in cat_clean or "water" in cat_clean or "access" in cat_clean:
        return "Housekeeping / Site Conditions"
    if "progress" in cat_clean or "work" in cat_clean or "activity" in cat_clean:
        return "Work Progress"
    return "Site Safety"


def normalize_confidence(conf: str) -> str:
    """Normalizes confidence string to HIGH, MEDIUM, or REQUIRES_PHYSICAL_VERIFICATION."""
    conf_clean = conf.strip().upper()
    if "PHYSICAL" in conf_clean or "VERIF" in conf_clean or "REQUIRED" in conf_clean or "NOT_DETERMINABLE" in conf_clean:
        return "REQUIRES_PHYSICAL_VERIFICATION"
    if "HIGH" in conf_clean:
        return "HIGH"
    if "MED" in conf_clean:
        return "MEDIUM"
    return "MEDIUM"


def normalize_risk_priority(prio: str) -> str:
    """Normalizes priority string to HIGH ATTENTION, MEDIUM ATTENTION, or LOW ATTENTION."""
    prio_clean = prio.strip().upper()
    if "HIGH" in prio_clean or "URGENT" in prio_clean or "CRITICAL" in prio_clean:
        return "HIGH ATTENTION"
    if "LOW" in prio_clean or "INFO" in prio_clean or "NORMAL" in prio_clean:
        return "LOW ATTENTION"
    return "MEDIUM ATTENTION"


def parse_inspection_json(json_input: str) -> InspectionReport:
    """
    Robustly parses JSON response from Gemini into a validated InspectionReport.
    Handles Markdown code blocks, raw JSON strings, non-dict structures, missing fields,
    and invalid values safely without crashing or inventing engineering data.
    """
    if not json_input or not isinstance(json_input, str) or not json_input.strip():
        return InspectionReport(summary="No visual inspection data provided.", observations=[])

    clean_text = json_input.strip()
    # Strip markdown code fencing if present
    if "```json" in clean_text:
        match = re.search(r"```json\s*(.*?)\s*```", clean_text, re.DOTALL)
        if match:
            clean_text = match.group(1).strip()
    elif "```" in clean_text:
        match = re.search(r"```\s*(.*?)\s*```", clean_text, re.DOTALL)
        if match:
            clean_text = match.group(1).strip()

    data: Any = {}
    try:
        data = json.loads(clean_text)
    except Exception:
        # Try to find outer JSON object {...}
        match = re.search(r"(\{.*\})", clean_text, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group(1))
            except Exception:
                data = {}
        else:
            data = {}

    if not isinstance(data, dict):
        data = {}

    raw_summary = data.get("summary")
    raw_site_activity = data.get("site_activity")

    summary = str(raw_summary).strip() if raw_summary and str(raw_summary).strip() else (
        str(raw_site_activity).strip() if raw_site_activity and str(raw_site_activity).strip() else "Visual inspection completed."
    )
    site_activity = str(raw_site_activity).strip() if raw_site_activity and str(raw_site_activity).strip() else (
        str(raw_summary).strip() if raw_summary and str(raw_summary).strip() else ""
    )
    raw_obs_list = data.get("observations")
    if not isinstance(raw_obs_list, list):
        raw_obs_list = []

    observations: List[ObservationRecord] = []
    for item in raw_obs_list:
        if not isinstance(item, dict):
            continue
        raw_cat = str(item.get("category") or "Site Safety")
        raw_conf = str(item.get("visual_confidence") or "MEDIUM")
        raw_prio = str(item.get("risk_priority") or "MEDIUM ATTENTION")
        raw_evidence = str(item.get("evidence_type") or "VISIBLE").strip().upper()
        if raw_evidence not in EVIDENCE_TYPES:
            raw_evidence = "VISIBLE"

        obs_text = str(item.get("observation") or "").strip()
        pot_issue = str(item.get("potential_issue") or "None identified").strip()
        phys_verif = str(
            item.get("physical_verification_required") or "Verify against project specifications."
        ).strip()
        rec_act = str(
            item.get("recommended_action") or "Conduct visual follow-up and on-site check."
        ).strip()

        rec = ObservationRecord(
            category=normalize_category(raw_cat),
            observation=obs_text,
            visual_confidence=normalize_confidence(raw_conf),
            potential_issue=pot_issue,
            physical_verification_required=phys_verif,
            recommended_action=rec_act,
            risk_priority=normalize_risk_priority(raw_prio),
            evidence_type=raw_evidence,
        )
        observations.append(rec)

    return InspectionReport(
        summary=summary,
        site_activity=site_activity,
        observations=observations,
    )


# ---------------------------------------------------------
# Phase 4C / Workshop Action: Deterministic Email Dispatch
# ---------------------------------------------------------
EMAIL_REGEX = re.compile(r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$")


def is_valid_email(email: str) -> bool:
    """Validates basic email structure safely without external libraries."""
    if not email or not isinstance(email, str):
        return False
    email = email.strip()
    if len(email) > 254 or len(email) < 5:
        return False
    return bool(EMAIL_REGEX.match(email))


def format_inspection_email_body(record: InspectionRecord) -> Tuple[str, str]:
    """
    Builds a concise, professional plain-text and HTML email notification from an InspectionRecord.
    Deterministic and 100% local (zero Gemini or external network calls).
    """
    subject = f"[CivilVision AI] Inspection Alert: {record.inspection_id} ({record.site_activity[:40]})"

    obs_lines = []
    for i, obs in enumerate(record.observations, 1):
        obs_lines.append(
            f"{i}. [{obs.risk_priority}] ({obs.category})\n"
            f"   - Observation: {obs.observation}\n"
            f"   - Potential Issue: {obs.potential_issue}\n"
            f"   - Physical Verification: {obs.physical_verification_required}\n"
            f"   - Recommended Action: {obs.recommended_action}"
        )
    obs_text = "\n\n".join(obs_lines) if obs_lines else "No specific observations recorded."

    plain_text = (
        f"CivilVision AI – Construction Site Visual Inspection Report\n"
        f"===========================================================\n"
        f"Inspection ID: {record.inspection_id}\n"
        f"Date/Time:     {record.timestamp}\n"
        f"Site Activity: {record.site_activity}\n\n"
        f"EXECUTIVE SUMMARY:\n"
        f"{record.executive_summary}\n\n"
        f"RISK PRIORITY METRICS:\n"
        f"- Total Observations: {record.total_observations}\n"
        f"- High Attention:     {record.high_attention_count}\n"
        f"- Medium Attention:   {record.medium_attention_count}\n"
        f"- Low Attention:      {record.low_attention_count}\n\n"
        f"KEY OBSERVATIONS & VERIFICATIONS:\n"
        f"---------------------------------\n"
        f"{obs_text}\n\n"
        f"ENGINEERING NOTICE:\n"
        f"{record.disclaimer}\n"
    )

    return subject, plain_text


def send_inspection_email(
    record: InspectionRecord,
    recipient_email: str,
    sender_email: Optional[str] = None,
    sender_password: Optional[str] = None,
    smtp_host: str = "smtp.gmail.com",
    smtp_port: int = 587,
    timeout: int = 15,
) -> Tuple[bool, str]:
    """
    Sends an inspection summary via Gmail SMTP using Python's built-in smtplib and email modules.
    Uses smtp.gmail.com:587 with STARTTLS as the primary method, with port 465 SSL as fallback.
    Handles missing secrets, invalid email addresses, SMTP failures, and empty inspection data gracefully.
    Does NOT make any Gemini calls.
    """
    import smtplib
    from email.message import EmailMessage

    # 1. Validate inspection data
    if record is None:
        return False, "No active inspection record available to send."

    # 2. Validate recipient address
    recipient = (recipient_email or "").strip()
    if not recipient:
        return False, "Recipient email address cannot be empty."
    if not is_valid_email(recipient):
        return False, f"Invalid recipient email address format: '{recipient}'."

    # 3. Validate sender credentials
    sender = (sender_email or "").strip()
    password = (sender_password or "").strip()

    if not sender or not password:
        return (
            False,
            "Gmail credentials are not configured. Please add GMAIL_ADDRESS and GMAIL_APP_PASSWORD "
            "to .streamlit/secrets.toml or Streamlit Community Cloud Secrets.",
        )

    if not is_valid_email(sender):
        return False, f"Configured sender email address is invalid: '{sender}'."

    # 4. Build message
    try:
        subject, body = format_inspection_email_body(record)

        msg = EmailMessage()
        msg["Subject"] = subject
        msg["From"] = sender
        msg["To"] = recipient
        msg.set_content(body)

        def _dispatch_starttls(host: str, port: int) -> None:
            with smtplib.SMTP(host, port, timeout=timeout) as server:
                server.ehlo()
                server.starttls()
                server.ehlo()
                server.login(sender, password)
                server.send_message(msg)

        def _dispatch_ssl(host: str, port: int) -> None:
            with smtplib.SMTP_SSL(host, port, timeout=timeout) as server:
                server.login(sender, password)
                server.send_message(msg)

        # 5. Dispatch: Primary STARTTLS (587) with SSL (465) fallback
        if smtp_port == 587:
            try:
                _dispatch_starttls(smtp_host, 587)
            except smtplib.SMTPAuthenticationError:
                raise
            except Exception as primary_err:
                # Fallback to SSL port 465 if primary connection/transmission fails
                try:
                    _dispatch_ssl(smtp_host, 465)
                except Exception:
                    # Raise primary error to preserve diagnostic details
                    raise primary_err
        elif smtp_port == 465:
            try:
                _dispatch_ssl(smtp_host, 465)
            except smtplib.SMTPAuthenticationError:
                raise
            except Exception as primary_err:
                # Fallback to STARTTLS port 587 if SSL fails
                try:
                    _dispatch_starttls(smtp_host, 587)
                except Exception:
                    raise primary_err
        else:
            # Custom port specified by caller
            _dispatch_starttls(smtp_host, smtp_port)

        return True, f"Inspection report successfully emailed to {recipient}!"

    except smtplib.SMTPAuthenticationError:
        return (
            False,
            "SMTP Authentication failed. Please verify that GMAIL_ADDRESS and GMAIL_APP_PASSWORD "
            "are correct. Make sure to use a 16-character Google App Password (not your primary password).",
        )
    except smtplib.SMTPConnectError as e:
        return False, f"Failed to connect to SMTP server ({smtp_host}:{smtp_port}): {e}"
    except smtplib.SMTPRecipientsRefused:
        return False, f"Recipient email address was refused by server: {recipient}"
    except (smtplib.SMTPException, OSError, TimeoutError) as e:
        return False, f"SMTP delivery error: {str(e)}"
    except Exception as e:
        return False, f"Unexpected error dispatching email: {str(e)}"


